"""update restaurant item relation

Revision ID: 8138dd4a77bd
Revises: 3de36b2201e2
Create Date: 2024-11-14 23:52:23.991673

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8138dd4a77bd'
down_revision = '3de36b2201e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('item', sa.Column('restaurant_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'item', 'restaurant', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'restaurant_id')
    op.drop_column('item', 'image')
    # ### end Alembic commands ###
