"""add restaurant book price

Revision ID: e6ed194ecd28
Revises: 82cfb6c58967
Create Date: 2024-11-15 00:50:26.869340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e6ed194ecd28'
down_revision = '82cfb6c58967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('restaurant', sa.Column('book_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant', 'book_price')
    op.drop_column('book', 'active')
    # ### end Alembic commands ###
